### ISSUE TITLE
Does mdslides support YAML Front Matter configurations ?

### ISSUE THREAD

**Issue by jaywhj** [MartenBE/mkslides#11]
Excuse me, does mdslides support YAML Front Matter configurations ?  I tried it and it didn't seem to work!
I know that mkslides.yml file can configure all the properties, but sometimes there are special cases, if I want to configure individual MD file properties, what do I do?

By the way, the last feedback about the math equation parsing and emoji parsing bugs, I fed back to the upstream reveal.js, and the math equation parsing bug was fixed the next day, and you can see the code update of the plugin from [reveal.js commit](https://github.com/hakimel/reveal.js/commit/5a275f223b59f06ec923b34ec0e5e551a6082a0d)

about the emoji parsing, because reveal.js does not cover it, so upstream reveal doesn't have this problem.

I see that reveal.js didn't change the code or modify the regular expression much, just added the filter tag for `code`, it turns out there were other tags that needed to be filtered, just adding the code tag solved it, hope that helps.

**Comment by jaywhj** [comment]
Yes，it currently only overrides the title.

Looking forward to your updates, but there's no rush, when you're free later, cheers

**Comment by MartenBE** [comment]
This will be fixed in https://github.com/MartenBE/mkslides/pull/18

**Comment by MartenBE** [comment]
Fixed in v0.1.34
