### ISSUE TITLE
Hi, mkslides 0.1.35 still has compilation errors, more than one!

### ISSUE THREAD

**Issue by jaywhj** [MartenBE/mkslides#21]
Hi, mkslides 0.1.35 still has compilation errors, more than one!

I updated the version and got an error the first time I compiled it.

<img width="881" alt="iShot_2024-11-27_20 03 20" src="https://github.com/user-attachments/assets/598b4dcc-bbb7-4cee-9585-cad93112264b">
There are no special cases for the configuration items in the `mkslides.yml` file, and they can be used before the update.

Next I commented out this configuration item in the yml file: `separator_charset: utf-8`, and other compilation errors appeared.

<img width="1438" alt="iShot_2024-11-27_20 06 08" src="https://github.com/user-attachments/assets/15349044-09b1-43d9-8197-a10532e58d3b">

Not sure what this error is about.

Next I checked the configuration items in mkslides.yml one by one, and finally found the reason, it turned out to be the configuration items in `revealjs`, after the update does not support the configuration of plugin attributes, before the update has always been able to use.

<img width="761" alt="iShot_2024-11-27_21 25 55" src="https://github.com/user-attachments/assets/53acf573-f227-4298-a99c-a6e157be6b14">

I have not added any new configurations for this, they were all available before, is this usage updated?

**Comment by MartenBE** [comment]
Also the markdown files

**Comment by MartenBE** [comment]
> I tested it and found that revealjs configuration item can't have any other plugin's attributes configured inside it, and changing it to another plugin's attributes doesn't work either, only revealjs' own attributes.

I could reproduce this, fix is in https://github.com/MartenBE/mkslides/pull/22

**Comment by jaywhj** [comment]
[mkslides.txt](https://github.com/user-attachments/files/17937114/mkslides.txt)

@MartenBE

**Comment by jaywhj** [comment]
The preprocessing feature is great, I tested it and it works great. i don't know how to write Python code, I used Claude to generate it for me, haha, great experience! 👍

**Comment by jaywhj** [comment]
Okay, thanks. All issues fixed 👍🏻
