### ISSUE TITLE
Encoding issue for emoji?

### ISSUE THREAD

**Issue by compressed** [MartenBE/mkslides#23]
**Describe the bug**
When running `mkslides serve ...` I have run into an error when the file contains any emoji, e.g., `:tada:`, `UnicodeEncodeError: 'charmap' codec can't encode character ...`.

Adding `encoding='utf-8'` [here](https://github.com/MartenBE/mkslides/blob/main/src/mkslides/markupgenerator.py#L355) and  [here](https://github.com/MartenBE/mkslides/blob/main/src/mkslides/markupgenerator.py#L359) seems to resolve the issue. Happy to make a PR if that's the correct fix.

**Expected behavior**
No error.

**Minimal reproducable example:**

```md
It's time to :tada:
```

**Version (please complete the following information):**
1.0.0 (latest from pip)

**Comment by MartenBE** [comment]
Hi @compressed , could you post the complete output?
If you want to make a PR, please go ahead! it the tests pass, I'll merge it and create a patch release :+1:

**Comment by MartenBE** [comment]
Further research seems to indicate that your solutions seems to be the best way forward: https://codereview.doctor/features/python/best-practice/file-open-write-encoding

**Comment by MartenBE** [comment]
Version 1.0.1 should solve this.

**Comment by compressed** [comment]
Thank you so much! Works now!
