### ISSUE TITLE
Hi, does MkSlides support the Markmap plugin?

### ISSUE THREAD

**Issue by jaywhj** [MartenBE/mkslides#24]
Hi, does mkslides support the [markmap](https://github.com/markmap/markmap) plugin for viewing mind maps directly in slides?  

I see [MkDocs](https://pypi.org/project/mkdocs/) has this plugin  [mkdocs-markmap](https://github.com/markmap/mkdocs-markmap), can you see if you can port it over without major modifications? it can be one of the features of your project.

**Comment by MartenBE** [comment]
You can try to insert it it using the plugin options. As this is very user specific, I consider this a wontfix as it would be too much feature creep atm and gives a lot of overhead to maintain in the future. I suggest you try to convert it into a Reveal.js plugin if necessary, which would be te better and a much cleaner solution.

MkSlides is a whole different program than MkDocs behind the scenes: we rely on Reveal.js while MkDocs generates its own HTML. Plugins between these are thus not transferrable.

**Comment by jaywhj** [comment]
Okay, thanks.
