### ISSUE TITLE
Where is the path to the configuration file mkslides.yml?

### ISSUE THREAD

**Issue by jaywhj** [MartenBE/mkslides#8]
hi，Where is the path to the configuration file mkslides.yml?

each md source file needs to be configured with an mkslides.yml？

**Comment by MartenBE** [comment]
Hi, you only need a single `mkslides.yml` file for the whole folder container `.md` files. You can see the example repository for University College Ghent at https://github.com/HoGentTIN/hogent-markdown-slides. This shows all the possibilities and an example structure.

**Comment by jaywhj** [comment]
> Hi, you only need a single `mkslides.yml` file for the whole folder containing the `.md` files. You can see the example repository for University College Ghent at https://github.com/HoGentTIN/hogent-markdown-slides. This shows all the possibilities and an example structure.

Thanks. It's done.
