### ISSUE TITLE
[bug] an inline span of code is parsed，but it should show the original code

### ISSUE THREAD

**Issue by jaywhj** [MartenBE/mkslides#9]
an inline span of code is parsed，but it should show the original code.
e.g, the inline span of `&#128516;` would be parsed as the emoji 😄, but it should show the utf8 character.

similarly, the math code in an inline span is parsed.
e.g, the inline span of `$ E=mc^2 $` would be parsed as the formula, but it should show the original code `$ E=mc^2 $`.

This problem can also cause other errors, such as build errors.:
because the inline code contains paths that don't exist, but I'm just going to demonstrate them, so include them in the inline code `` 
<br />
<img width="1438" alt="iShot_2024-11-07_00 26 58" src="https://github.com/user-attachments/assets/8cea4438-6809-4b1c-84ef-8689ea5d4ea4">

**Comment by MartenBE** [comment]
Could you create a minimal markdown file that reproduces this error?

**Comment by jaywhj** [comment]
> Could you create a minimal markdown file or directory that reproduces this error?

Okay, here's the source file.
<br />
[test.md](https://github.com/user-attachments/files/17651229/test.md)

**Comment by MartenBE** [comment]
Allright, that's a good example file. It is important to know that MkSlides actually doesn't process the markdown itself, it delegates that to Reveal.js. MkSlides creates a wrapper around it so it is easy to use and helps with files, images, live reload, etc ... .

- Test 1: Math is processed upstream by Reveal.js as seen in https://revealjs.com/math/ . So it is best to create an issue there.
- Test 2:
  - The :qwerty: emojis are processed by an external libraries, which replaces all detected volid emoji codes. This library doesn't consider the format of the text (markdown, html, code, ...). So this would require introducing something like treesitter which is kinda overkill for the moment ... I would like to keep the interfering with the MarkDown to a minimum and to leave as much as possible to Reveal.js. Especially considering the next point
  - The &#qwerty; emoji's are correctly rendered as text in the HTML source, it's the browser that parses it to an emoji or entity. This isn't fixable by MkSlides.
- Test 3: This also seems an upstream problem as we don't parse the markdown to HTML.
- Test 4 & 5: Yes, this is on me. I should be able to adjust the link regex to detect anchor links.

**Comment by MartenBE** [comment]
Testcase 4 and 5 should be solved in v0.1.32

**Comment by jaywhj** [comment]
Okay, great 👍.
I'll submit all issues to Reveal.js except Test 4 and 5.

**Comment by jaywhj** [comment]
> v0.1.32

I updated to version v0.1.32 and found that it still causes build errors.
‘url-1, url-2 and url-3’ will cause a build error.

the markdown code is written like this：

use `[url-name](url-1)` show a hyperlink.

```html
<img src="url-2" style="zoom:50%;" />
```

use `![img-name](url-3)` show an image.
<br />
<img width="424" alt="iShot_2024-11-07_13 11 19" src="https://github.com/user-attachments/assets/245aa2c9-7073-46c2-90da-0b93b46a427c">

**Comment by MartenBE** [comment]
Yes, at the moment we use simple regexps to find out which links are present in markdown. To mitigate your problem, we would have to rewrite the parsing using a markdown parser or something like treesitter to get the AST and only use the regexp on non coding blocks. This is not an easy fix I'm afraid, I'll put it on the todo list, but it will take a while.

**Comment by jaywhj** [comment]
> Yes, at the moment we use simple regexps to find out which links are present in markdown. To mitigate your problem, we would have to rewrite the parsing using a markdown parser or something like treesitter to get the AST and only use the regexp on non coding blocks. This is not an easy fix I'm afraid, I'll put it on the todo list, but it will take a while.

Okay, no rush. Come on.👍

**Comment by jaywhj** [comment]
One more question, 
what path is the upstream resource package installed in?  for example, where is the path to reveal.js?
I want to add some plugins, so I want to know the resource file paths.

**Comment by MartenBE** [comment]
@jaywhj I have pushed v.0.1.33 that should solve this issue: see the tests at https://github.com/MartenBE/mkslides/blob/2414184d05cb890d6762a763b868105401e1e52b/tests/test_files/someslides.md?plain=1#L90

**Comment by MartenBE** [comment]
> One more question, what path is the upstream resource package installed in? for example, where is the path to reveal.js? I want to add some plugins, so I want to know the resource file paths.

If you use build, you can check the folder. I have only tested absolute paths for plugins as that is the most used use case. You can specify those in the `mkslides.yml` (see the example repo)

**Comment by jaywhj** [comment]
> @jaywhj I have pushed v.0.1.33 that should solve this issue: see the tests at
> 
> https://github.com/MartenBE/mkslides/blob/2414184d05cb890d6762a763b868105401e1e52b/tests/test_files/someslides.md?plain=1#L90

Yes, it's solved. Great.👏，and custom plugins is also available. 👍

**Comment by jaywhj** [comment]
@MartenBE Excuse me, one more question🙏:
Adding custom plugins is available, but some plugins need to configure more parameters, how is this parameter written in the mkslides.yml file? 
for example, configure this plugin: [reveal.js-toolbar](https://github.com/denehyg/reveal.js-toolbar)
